sudo: false
dist: trusty
language: java
jdk:
- oraclejdk8
os:
- linux
script:
- ./gradlew build
- cd $TRAVIS_BUILD_DIR
- chmod +x ./deploy.sh
deploy:
- provider: script
  script: "./deploy.sh"
  skip_cleanup: true
  on:
    branch: master
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_API_TOKEN
  keep-history: true
  local-dir: "./docs/"
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_04827ca67184_key -iv $encrypted_04827ca67184_iv
  -in encrypted.enc -out secring.gpg -d
