language: java

jdk:
  - oraclejdk8          // tells Travis to use Java 8

# taken from Gradle guide on travis-ci.org
# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: oAMTvHcVECPQkIu0hmvjUgkmmNp1EQND1+AlOif3dJWV/dg8dC8Z/m0WTgdg7xWilf+gWFxlELgKivOE5WmMwrziuLb0vsSi7z37N7gbFAqemo5/XcT/+wx3XdSl81yxdJSbnHw4QKcGC4z2i7aHntz9wDr44rHWv17nCQ73ntdvgHMHD3hmAOM0kgihtXJPXqVUjpmvYfe7h3d9eclcH9hV+vmxTvos37Dvj6oQwZCuDUUPjjOppS+OUjIUu1ynfcFsdQPcfjAEDjZvd81Ms1sPOeWybBj933cjrFMHcUWHhmG/+ydbh1ILDSj1YeFT5bxJh/cViRgQ4XQB/eJYehYCeXv+C2lbSuBKTwdXT31GLdr5O0szOpePTHsMelknscnVJI6/OT+yj/LkbPuO4oqbKF0Kbw5TzYgax7p9luDu+Kp/buGUm9nnX8jHuhChZhu8xhiBn4eWPAlUhuC+IzfAzXy6U29REH0FIHAUuOhajlvo7zIu9JbI+oZW4ZJKeI9wrGrgPl3H0mwq/uxsTBJt8975qCTpceVPuyl3wHh72qz2MHsDVW/O7mWPNhSR8kqnXAXNvdHNVQkH6pWw7lbfIsjvxsQNe2FCJ1SUvfIXWzJ5aaw0lF/JMbKWVcB5a3/MRVlJrWG7niFlaV9cw8FCoxuQhPTCwfznHwJbIqA=
  - secure: PzGH9QlOZ/dW0Zn+zhvncnTpOjTLT1++pxIqFhBWIEfzGiyPs27H3rk2gZq1VQkoaUUe3j5MOUMPv0khVh/Q5HGAOHTC6EpHSq85F79MwTf65SXdrm4xtcBEJx3DYAa9vogQOYnCAVYHyX7U3vd8A+/B3c/6nNHqy5VrdOvrAYdbN/6901a/WG8QMRKwlSZIFSYI+krz3ZEu5yokPSHB/xh8nyL/cMZtCa6H/+msQTo3dywZ6okSdfJcz1JKeyx6iHnNMPyE+XpZLC4C9vWd1nppI0B2R8SSQCGmSsV58Ec9V6voIVjcWiQ1yl9Qlv6Io3BbzH70Gmjv91hAlc7ewM4BQGT41Jz2vWhilNTksHqRLPFTBlS+3DhIP8K+aWg5w4/rKxIv/HUjacsM5GyeXq65meAdv6+ltsvx8KDXvVY0R4Ag4UpkUBRoQwTTzyn/KGBg+SgK9RVT+xHvGll4oUECPs5JItN5YlsLqkdr4LSijtjMNTtlmwbwAf450KXCty+RWr8hV7LcA5vLd4FpnXPCiV1bhKpQTF6VNoLkqyFe+JtcR5OJQCz7143Oq2X9vvm4wyMusndpS8F+gQxMBHXhHWDtpS0o7fdt2Pct3ll0UlbipfWkQF2ePVIAj91AyVmxfvrGDDLKBU6maMgAkfNrFUo2aUAfei0bQJvrX7w=

after_success:
 -./gradlew pP publish