language: java

jdk:
  - oraclejdk8          // tells Travis to use Java 8

# taken from Gradle guide on travis-ci.org
# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

after_success:
 - ./gradlew pP publish
