language: java
jdk:
- oraclejdk8          // tells Travis to use Java 8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- cd $TRAVIS_BUILD_DIR
- chmod +x ./deploy.sh
deploy:
- provider: script
  script: "./deploy.sh snapshot"
  skip_cleanup: true
  on:
    branch: develop
- provider: script
  script: "./deploy.sh release"
  skip_cleanup: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_04827ca67184_key -iv $encrypted_04827ca67184_iv
  -in encrypted.enc -out secring.gpg -d
env:
  global:
  - secure: MG8InbknzeXejbwzxG+DKg6JaMXLA/fn2yx4G2fa4SIsjf4MEzEpFFIpmmvsc4sqGnw4X+DJfgyBqxjemAsoJIeaprEX48HURhBbwCwCJTQCNmWgm/VG5f7ePkcWgcyyKiiMGpIhqm0sQgtngLaQWboFlikJ3S/d4/1IJDgyJV4lG4ebJ02uX13UeGmw9d0iKz9VHMLRC50nG+ouB0NVcQervxS4/UoAGZqL8xIgnGYy9R7utxkpKKtbsfNoxTsOoeU/LGuEM4YEYYaXuqtuX/B9JGLw8v3brIVbLFpTgVEk7JEMn+X14uWP4M/0AYQ4Ht1MJIDCzOo2t52z93EIJAm+GOaYPhLX7KnbWKTtEXDiPjsmrGWiclaV0/2/TTpQ60eB+iapPTvOm2Q2WMs6m6SMOibw/8Mw3PUK7m7rQBMOw44WlC3Gsa5EWEK/U3KNBji9uCnleS7REoC4K/49/EeXtFkvw0A2WyHKkb3EKSenHzk7nTjnxrU3zfZEv3vq4nVYBwwcyh2vLq62ZQJa5lexee8jS61E+NexRT5z+AdLygvzc6/I1Z/YCg6aPLn9dQ1i6H3Q51k8AcHhQacM5Xop5MJPRKQLkdSTSzPQKXTe1LbSiGja6FnJUdOeAKemyirgIBbLmHyh/a1FPuBYiQgyCmXnTlVWXDc3NrWEb4c=
  - secure: W42+3wBWVuWRMMij15/0fUtWUa89f4VVy8lBJMnkutP4onyBkdoco5MPj2xtgRFdr7aWv2hyBYI9q+oK0UsOXnNHauT/bxRg1JdiRAU8Ovuieb3CSyEkxLD9ZEbLToOg7BPmJaHbVlPCfxSPGde98mvhRvYGfORrRfoeTEqQCOqEQaRA8X5nJwJHWBKzOYDn9ao/4GXsSajMJVgdSiWy2753UJtQbQTddNlhOTU5uq3bfqElO+ulRVnJRwAx/+Im1bYO/8E9nnHMyFXxAUbUF1NLYcLnA1sTGtoe8ugizByuVlmyg3ECOj7fmvjquE4uexm8zsVy7DxHbbWtCZd9rsOpZDczOnL1+RwQmELU7FdRoPWhZ93noW/OOT1dpk1H7ffvYyh3GW+5iyPpli6ztiDiDfJDkfnJNjxWz5Fnd0X51LFhZ2C0KB5QwA7VLdnwmkYsMWZLkKiGb01vNelsREdTrybSUeIJX+rkIxv8ySIXR3QHX6mOVCkwoo8e3dzisCduE4qxKAjXbcE3FI4iXoILajwV/Tqv8BLzXXYsdWPdqObOOiGFFpGEZCsf0eua7iX7PssJZlNdjMqPv4pDfjcafwwI6irwDNtNL9njqjQnP6SGE46VZBS0ghxdxG+Isr4o/K0XQWIHRkoagxyBtiv/RIcaWRnfMqJccuB5Fsg=
  - secure: O+7b1RhhyFeE1slqnrwN2z3Ovh18EOUIkKUYOdEpLSxtZw3t1nW+P8onriLLmIkUIlxqCV3JvBOdl3izo0hG3MR7DgvdfHeJJOUmnTzpM4Qc43AYvQ7hNDOXu0g9DFVhDirGEo4Z9/1+XBA+ncm/ETKAss7ppnE1Pn1bCbJW1zNJ8YTWfm9yw0tFZHf7MO43npOG2OA18jVJZdyl33vWjhF6jKPGil52w83LXEiYCCOG8Nnt2GVy38ndNZIqHKdaRKUMZ3OGllxJSChaiz8h7GKJz5TuxcvGzGkih2Kdk2z9hn9M7l5ov/EcnoCxDJemb39OVkUARyFRxe2ZLVRpq3rUdu/oi7E3ZMWT0zfm/RUKi5o3eZ1obhLnfLi/dXPpBsViF81EtJ9gKUz/eb0DycvVSMKFxDvyXxX6YxujkQYuy9nfg4BwpX/v+TvsmNTTV6/SncjFhd/M3gvjkNdVI24WUuIsbzH77P8E+UJZ2Rv1lOVovuj5Yl5kr1ijHsNiv2ssbT4ahm8L4SJ93zh3Yra+xeRhQAtn7BZafbQv+SVCEJe8JX88DFlXbMkJwtEXssvbx+mxTnvl2KkUMP7PVkxBksh9mZNRHbTTYMadcG8q+h+9R1CwZGN2XUb9tIRO1tcECC2f4XllQONx3/iR60ItX/BLpl8sF/ngFGMWbUw=
