/* Copyright (c) 2017-present Acrolinx GmbH */

package com.acrolinx.sidebar.dita;

import static org.junit.Assert.assertTrue;

import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;

import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;

import org.junit.Test;
import org.xml.sax.SAXException;

public class DitaBuilderTest
{
    @SuppressWarnings("ConstantConditions")
    @Test
    public void testDitaBuilder() throws IOException, ParserConfigurationException, SAXException, URISyntaxException
    {
        final ClassLoader classLoader = getClass().getClassLoader();
        final File file = new File(classLoader.getResource("DITA/WorldTimePro.ditamap").getFile());
        final DitaBuilder ditaBuilder = new DitaBuilder(file.toURI().toURL(), null);
        try {
            final String andResolveAllTopicRefs = ditaBuilder.findAndResolveAllTopicRefs();
            assertTrue(andResolveAllTopicRefs.replace("\r", "\n").replace("\n\n", "\n").contains(
                    ("<map id=\"map_usingworldtimepro\" title=\"Using World Time Pro\">\n" + "\t<title>\n"
                            + "    Using\n" + "    <term>World Time Pro</term>\n" + "\t</title>\n" + "\t<topicmeta>\n"
                            + "\t\t<shortdesc>\n" + "      This documentation suite explains how to use the\n"
                            + "      <term>World Time Pro</term>.\n" + "    </shortdesc>\n"
                            + "\t\t<author type=\"creator\">Heather Wymer</author>\n" + "\t\t<copyright>\n"
                            + "\t\t\t<copyryear year=\"2008\"/>\n"
                            + "\t\t\t<copyrholder>M-Azlan Software</copyrholder>\n" + "\t\t</copyright>\n"
                            + "\t\t<critdates>\n" + "\t\t\t<created date=\"8 Oct 2008\"/>\n"
                            + "\t\t\t<revised modified=\"25 Oct 2008\"/>\n" + "\t\t</critdates>\n"
                            + "\t\t<audience audience=\"all\"/>\n" + "\t\t<keywords>\n"
                            + "\t\t\t<keyword>World Time Pro</keyword>\n"
                            + "\t\t\t<keyword>Date Analysis Engine</keyword>\n"
                            + "\t\t\t<keyword>Standard/Military Time Converter</keyword>\n"
                            + "\t\t\t<keyword>military time</keyword>\n"
                            + "\t\t\t<keyword>Fraction Converter</keyword>\n"
                            + "\t\t\t<keyword>Fraction Creator</keyword>\n" + "\t\t\t<keyword>standard time</keyword>\n"
                            + "\t\t\t<keyword>hours</keyword>\n" + "\t\t\t<keyword>minutes</keyword>\n"
                            + "\t\t\t<keyword>seconds</keyword>\n" + "\t\t\t<keyword>support</keyword>\n"
                            + "\t\t\t<keyword>install</keyword>\n" + "\t\t</keywords>\n" + "\t\t<prodinfo>\n"
                            + "\t\t\t<prodname>World Time Pro</prodname>\n" + "\t\t\t<vrmlist>\n"
                            + "\t\t\t\t<vrm version=\"2\"/>\n" + "\t\t\t</vrmlist>\n" + "\t\t</prodinfo>\n"
                            + "\t</topicmeta>\n"
                            + "\t<keydef keys=\"product_name\" processing-role=\"resource-only\">\n"
                            + "\t\t<topicmeta>\n" + "\t\t\t<keywords>\n" + "\t\t\t\t<keyword>World Time Pro</keyword>\n"
                            + "\t\t\t</keywords>\n" + "\t\t</topicmeta>\n" + "\t</keydef>\n"
                            + "\t<keydef format=\"dita\" href=\"AboutWorldTimePro.xml\" keys=\"about_world_time_pro\" navtitle=\"Introduction to World Time Pro\" processing-role=\"resource-only\" scope=\"local\" type=\"concept\"/>\n"
                            + "\t<topicref format=\"dita\" href=\"AboutWorldTimePro.xml\" locktitle=\"yes\" navtitle=\"About World Time Pro\" scope=\"local\" type=\"concept\">\n"
                            + "\t<topicrefcontent>\n" + "      <concept id=\"worldtimepro\"> \n"
                            + "  <title>Introduction to \n" + "\t <term>World Time Pro</term>\n" + "        </title> \n"
                            + "  <shortdesc>This topic explains the tasks you can perform with \n"
                            + "\t <term>World Time Pro</term>. \n" + "  </shortdesc> \n" + "  <prolog> \n"
                            + "\t <author type=\"creator\">Heather Wymer</author>\n" + "\t <copyright> \n"
                            + "\t\t<copyryear year=\"2008\"/> \n" + "\t\t<copyrholder>M-Azlan Software</copyrholder> \n"
                            + "\t </copyright> \n" + "\t <critdates> \n"
                            + "\t\t<created date=\"6 Oct 2008\"/> </critdates>\n" + "\t <metadata> \n"
                            + "\t\t<prodinfo> \n" + "\t\t  <prodname>World Time Pro</prodname> \n"
                            + "\t\t  <vrmlist> \n" + "\t\t\t <vrm version=\"2 trial\"/> \n" + "\t\t  </vrmlist> \n"
                            + "\t\t</prodinfo> </metadata>\n" + "  </prolog> \n" + "  <conbody> \n" + "\t <p> \n"
                            + "\t\t<term>World Time Pro</term> is an easy way to add, subtract, multiply and\n"
                            + "\t\tdivide units of time. Adding and subtracting hours, minutes and seconds can be\n"
                            + "\t\ttricky - there are 60 minutes in an hour, but how many are in 5.75 hours? \n"
                            + "\t\t<term>World Time Pro</term> quickly and accurately solves this and any\n"
                            + "\t\tother time-related problems for you. \n" + "\t </p> \n" + "\t <p>Using \n"
                            + "\t\t<term>World Time Pro</term>, you can: \n" + "\t </p> \n"
                            + "\t <ul id=\"ul_3247DFCC5A0C4065A930EC66BE52214A\"> \n"
                            + "\t\t<li id=\"li_789FDA4EBAAC48A18782F26B37D57F77\">add, subtract, multiply or\n"
                            + "\t\t  divide periods of time \n" + "\t\t</li> \n"
                            + "\t\t<li id=\"li_0566DB736E5E416E9EBDE34954D44620\">convert large numbers of\n"
                            + "\t\t  minutes or seconds to hours this is errror \n" + "\t\t</li> \n"
                            + "\t\t<li id=\"li_E3E5F2549B18476DA2C8E06E4A85A014\">convert time in fractions to\n"
                            + "\t\t  time in hours, minutes and seconds \n" + "\t\t</li> \n"
                            + "\t\t<li id=\"li_23F7E7C4523D4E6F9278533DBF08A2EA\">calculate the day of the\n"
                            + "\t\t  week that a particular date falls on \n" + "\t\t</li> \n"
                            + "\t\t<li id=\"li_1A910B2CEE634DD3B0DB237CDDB4BAAE\">convert to and from \n"
                            + "\t\t  <term>military time</term> \n" + "\t\t</li> \n" + "\t </ul> \n" + "\t <p>\n"
                            + "            <term>World Time Pro</term> also features easy-to-use Help and a\n"
                            + "\t\ttroubleshooting section to ensure that you're up and calculating in no time! \n"
                            + "\t </p>\n" + "\t <p>\n" + "            <?xm-replace_text Paragraph?>\n" + "\t </p> \n"
                            + "  </conbody>\n" + "</concept>\n" + "    </topicrefcontent>\n" + "  </topicref>\n"
                            + "\t<topicref format=\"dita\" href=\"Tasks/CalculatingTime.xml\" locktitle=\"yes\" navtitle=\"Calculating time\" scope=\"local\" type=\"task\">\n"
                            + "\t\t<topicref format=\"dita\" href=\"Tasks/CalculatingHoursInMinutesSeconds.xml\" locktitle=\"yes\" navtitle=\"Calculating the hours in a large number of minutes or seconds\" scope=\"local\" type=\"task\">\n"
                            + "      <topicrefcontent>\n" + "        <task id=\"calculatinghoursinminutessec\"> \n"
                            + "  <title>Calculating the hours in a large number of minutes or seconds</title> \n"
                            + "  <shortdesc>This topic describes how to use \n"
                            + "\t <term>World Time Pro</term> to calculate how many hours, minutes and\n"
                            + "\t seconds are in a large number of minutes or seconds.\n" + "  </shortdesc> \n"
                            + "  <prolog> \n" + "\t <author type=\"creator\">Heather Wymer</author>\n"
                            + "\t <critdates> \n" + "\t\t<created date=\"5 Oct 2008\"/> </critdates>\n"
                            + "\t <metadata> \n" + "\t\t<keywords> \n"
                            + "\t\t  <keyword>main calculation pane</keyword> \n" + "\t\t  <keyword>hours</keyword> \n"
                            + "\t\t  <keyword>minutes</keyword> \n" + "\t\t  <keyword>seconds</keyword> \n"
                            + "\t\t</keywords> \n" + "\t\t<prodinfo> \n"
                            + "\t\t  <prodname>World Time Pro</prodname> \n" + "\t\t  <vrmlist> \n"
                            + "\t\t\t <vrm version=\"2 trial\"/> \n" + "\t\t  </vrmlist> \n"
                            + "\t\t</prodinfo> </metadata>\n" + "  </prolog> \n" + "  <taskbody> \n"
                            + "\t <context id=\"context_0DBA0304F3A04B1BB22486488506E6D6\">This procedure\n"
                            + "\t\tdescribes an easy and accurate way to calculate how many hours, minutes and\n"
                            + "\t\tseconds are in a large number of minutes or seconds.\n" + "\t </context> \n"
                            + "\t <steps id=\"steps_E23547BD3FF1486C8129EF9423B40642\"> \n"
                            + "\t\t<step id=\"step_C7B4B375E5DB42ED8B857FA181ADCFBA\"> \n" + "\t\t  <cmd>In the \n"
                            + "\t\t\t <wintitle>main calculation pane</wintitle>, do one of the following\n"
                            + "\t\t\t in the upper row of entry fields:\n" + "\t\t  </cmd> \n"
                            + "\t\t  <choices id=\"choices_0BD145CF1FEA48D48092C5E0740D5614\"> \n"
                            + "\t\t\t <choice id=\"choice_FECCD8A517154D4CA319CDF4C5726485\">Type the minutes\n"
                            + "\t\t\t\tyou want to convert in the \n" + "\t\t\t\t<uicontrol>Min</uicontrol> field.\n"
                            + "\t\t\t </choice> \n"
                            + "\t\t\t <choice id=\"choice_04147DE3B6334174A7CFCB7BF5634393\">Type the seconds\n"
                            + "\t\t\t\tyou want to convert in the \n"
                            + "\t\t\t\t<uicontrol>Seconds</uicontrol> field.\n" + "\t\t\t </choice> \n"
                            + "\t\t  </choices> \n" + "\t\t</step> \n"
                            + "\t\t<step id=\"step_A8C719E4DC10489CAA42EB60F968664A\"> \n" + "\t\t  <cmd>Click \n"
                            + "\t\t\t <uicontrol>Plus</uicontrol>.\n" + "\t\t  </cmd> \n" + "\t\t</step> \n"
                            + "\t\t<step id=\"step_3AA759CD783844828A0B5544762305DD\"> \n" + "\t\t  <cmd>Click \n"
                            + "\t\t\t <uicontrol>Equals</uicontrol>.\n" + "\t\t  </cmd> \n" + "\t\t</step> \n"
                            + "\t </steps> \n"
                            + "\t <result id=\"result_DBBAD7E8C0B845908691B5C48D0D3340\">The number of minutes\n"
                            + "\t\tor seconds appears in hours, minutes and seconds in the \n"
                            + "\t\t<uicontrol>result fields</uicontrol>.\n" + "\t </result> \n"
                            + "\t <example id=\"example_CDFA267EB6ED4708AD560A59714F7E9A\">For example, to\n"
                            + "\t\tcalculate how many hours, minutes and seconds are in 2607 seconds, type \n"
                            + "\t\t<userinput>2607</userinput> in the \n"
                            + "\t\t<uicontrol>Seconds</uicontrol> field in the upper row of entry fields.\n"
                            + "\t\tClick \n" + "\t\t<uicontrol>Plus</uicontrol>, then click \n"
                            + "\t\t<uicontrol>Equals</uicontrol>. The result of \n"
                            + "\t\t<systemoutput>43 min 27 sec</systemoutput> appears in the \n"
                            + "\t\t<uicontrol>result fields</uicontrol>.\n" + "\t </example> \n" + "  </taskbody>\n"
                            + "</task>\n" + "      </topicrefcontent>\n" + "    </topicref>\n"
                            + "\t\t<topicref format=\"dita\" href=\"Tasks/CalculatingElapsedTime.xml\" locktitle=\"yes\" navtitle=\"Calculating elapsed time\" scope=\"local\" type=\"task\">\n"
                            + "      <topicrefcontent>\n" + "        <task id=\"calculatingelapsedtime\"> \n"
                            + "  <title>Calculating \n" + "\t <term>elapsed time</term>\n" + "          </title> \n"
                            + "  <shortdesc>This topic describes how to calculate the \n"
                            + "\t <term>elapsed time</term> between two different times of the day, such as\n"
                            + "\t the length of time between 11.50 am and 4.23 pm.\n" + "  </shortdesc> \n"
                            + "  <prolog> \n" + "\t <author type=\"creator\">Heather Wymer</author>\n"
                            + "\t <critdates> \n" + "\t\t<created date=\"4 Oct 2008\"/> </critdates>\n"
                            + "\t <metadata> \n" + "\t\t<keywords> \n" + "\t\t  <keyword>military time</keyword> \n"
                            + "\t\t  <keyword>elapsed time</keyword> \n" + "\t\t  <keyword>hours</keyword> \n"
                            + "\t\t  <keyword>minutes</keyword> \n" + "\t\t  <keyword>seconds</keyword> \n"
                            + "\t\t  <keyword>main calculation pane</keyword> \n" + "\t\t</keywords> \n"
                            + "\t\t<prodinfo> \n" + "\t\t  <prodname>World Time Pro</prodname> \n"
                            + "\t\t  <vrmlist> \n" + "\t\t\t <vrm version=\"2\"/> \n" + "\t\t  </vrmlist> \n"
                            + "\t\t</prodinfo> </metadata>\n" + "  </prolog> \n" + "  <taskbody> \n"
                            + "\t <prereq id=\"prereq_B78E8A27727D40C9AD95A04F07B46EE8\">Use the \n"
                            + "\t\t<wintitle>Standard/Military Time Converter</wintitle> to convert \n"
                            + "\t\t<term>standard times</term> to \n"
                            + "\t\t<term>military times</term> before beginning this procedure.\n" + "\t </prereq> \n"
                            + "\t <context id=\"context_D250057A362E4D38AE692930F555572A\">It can be difficult\n"
                            + "\t\tto work out how long has passed between two times of day, especially if one\n"
                            + "\t\ttime is in the morning and the other in the evening. This procedure explains\n"
                            + "\t\thow to use the \n" + "\t\t<term>World Time Pro</term> to easily calculate the \n"
                            + "\t\t<term>elapsed time</term> between two times of day.\n" + "\t </context> \n"
                            + "\t <steps id=\"steps_D330E6F1F99443E8B406413BA071E50C\"> \n"
                            + "\t\t<step id=\"step_6575D6439896412DBA9F519BAF8B5A6C\"> \n" + "\t\t  <cmd>In the \n"
                            + "\t\t\t <wintitle>main calculation pane</wintitle>, type the later time of\n"
                            + "\t\t\t day in the \n" + "\t\t\t <uicontrol>Hour</uicontrol> and \n"
                            + "\t\t\t <uicontrol>Min</uicontrol> fields in the upper row of entry fields.\n"
                            + "\t\t  </cmd> \n" + "\t\t  <info>\n"
                            + "\t\t\t <note type=\"attention\">The time must be in \n"
                            + "\t\t\t\t<term>military time</term>.\n" + "\t\t\t </note>\n" + "\t\t  </info> \n"
                            + "\t\t</step> \n" + "\t\t<step id=\"step_F1C87E68887647208B92722644F38944\"> \n"
                            + "\t\t  <cmd>Click \n" + "\t\t\t <uicontrol>Minus</uicontrol>.\n" + "\t\t  </cmd> \n"
                            + "\t\t</step> \n" + "\t\t<step id=\"step_E3719AD26CCB48C2B3D954E2E54D39C0\"> \n"
                            + "\t\t  <cmd>Type the earlier time of day in the \n" + "\t\t\t <uicontrol>Hour \n"
                            + "\t\t\t </uicontrol>and \n"
                            + "\t\t\t <uicontrol>Min</uicontrol> fields in the lower row of entry fields.\n"
                            + "\t\t  </cmd> \n" + "\t\t  <info>\n"
                            + "\t\t\t <note type=\"attention\">The time must be in \n"
                            + "\t\t\t\t<term>military time</term>.\n" + "\t\t\t </note>\n" + "\t\t  </info> \n"
                            + "\t\t</step> \n" + "\t\t<step id=\"step_73D750F72DE44939A99F0A6CF277D456\"> \n"
                            + "\t\t  <cmd>Click \n" + "\t\t\t <uicontrol>Equals</uicontrol>.\n" + "\t\t  </cmd> \n"
                            + "\t\t</step> \n" + "\t </steps> \n"
                            + "\t <result id=\"result_EA7F0BC713D84AADBF9D574B39779A06\">The elapsed time\n"
                            + "\t\tappears in the \n" + "\t\t<uicontrol>result fields</uicontrol>.\n"
                            + "\t </result> \n"
                            + "\t <example id=\"example_CD72F58DC23A4AEBB93AF0B1FD368E57\">For example, to\n"
                            + "\t\tcalculate how much time has passed between 11.50 am and 4.23 pm, use the \n"
                            + "\t\t<wintitle>Standard/Military Time Converter</wintitle> to convert the\n"
                            + "\t\ttimes to \n"
                            + "\t\t<term>military time</term>. 4.23 pm becomes 16.23, and 11.50 am becomes\n"
                            + "\t\t11.50. Type \n"
                            + "\t\t<userinput>16 23</userinput> in the upper row of entry fields, click \n"
                            + "\t\t<uicontrol>Minus</uicontrol>, and type \n"
                            + "\t\t<userinput>11 50</userinput> in the lower row of entry fields. Click \n"
                            + "\t\t<uicontrol>Equals</uicontrol>. The result of \n"
                            + "\t\t<systemoutput>4 hours 33 min</systemoutput> appears in the \n"
                            + "\t\t<uicontrol>result fields</uicontrol>.\n" + "\t </example> \n" + "  </taskbody>\n"
                            + "</task>\n" + "      </topicrefcontent>\n" + "    </topicref>\n"
                            + "\t\t<topicref format=\"dita\" href=\"Reference/WorldTimeProGUI.xml\" locktitle=\"yes\" navtitle=\"The World Time Pro window\" scope=\"local\" type=\"reference\">\n"
                            + "      <topicrefcontent>\n" + "        <reference id=\"worldtimeprogui\"> \n"
                            + "  <title>The<wintitle> World Time Pro window</wintitle>\n" + "          </title> \n"
                            + "  <shortdesc>This topic describes the buttons and fields in the \n"
                            + "\t <wintitle>World Time Pro window</wintitle>. \n" + "  </shortdesc> \n"
                            + "  <prolog> \n" + "\t <author type=\"creator\">Heather Wymer</author>\n"
                            + "\t <copyright> \n" + "\t\t<copyryear year=\"2008\"/> \n"
                            + "\t\t<copyrholder>M-Azlan Software</copyrholder> \n" + "\t </copyright> \n"
                            + "\t <critdates> \n" + "\t\t<created date=\"5 Oct 2008\"/> </critdates>\n"
                            + "\t <metadata> \n" + "\t\t<keywords> \n"
                            + "\t\t  <keyword>World Time Pro window</keyword> \n"
                            + "\t\t  <keyword>interface</keyword> \n" + "\t\t  <keyword>hours</keyword> \n"
                            + "\t\t  <keyword>minutes</keyword> \n" + "\t\t  <keyword>seconds</keyword> \n"
                            + "\t\t  <keyword>Main calculation pane</keyword> \n"
                            + "\t\t  <keyword>Fraction Creator pane</keyword> \n"
                            + "\t\t  <keyword>Fraction Converter pane</keyword> \n" + "\t\t</keywords> \n"
                            + "\t\t<prodinfo> \n" + "\t\t  <prodname>World Time Pro</prodname> \n"
                            + "\t\t  <vrmlist> \n" + "\t\t\t <vrm version=\"2 trial\"/> \n" + "\t\t  </vrmlist> \n"
                            + "\t\t</prodinfo> </metadata>\n" + "  </prolog> \n" + "  <refbody> \n"
                            + "\t <section id=\"section_CE42C3FF9D494B11BBB1BED3FAC724A4\"> \n"
                            + "\t\t<title>The World Time Pro window</title> \n"
                            + "\t\t<p platform=\"windowsxp windows2000\">\n"
                            + "                <image href=\"../Images/win/WorldTimeProGUI.png\" id=\"image_22E3B8D7119E4F18ADB81029312D6405\" width=\"813px\"> \n"
                            + "\t\t\t <alt>This graphic shows the fields and buttons in the main \n"
                            + "\t\t\t\t<wintitle>World Time Pro window</wintitle>. The window has a \n"
                            + "\t\t\t\t<wintitle>main calculation pane</wintitle>, a \n"
                            + "\t\t\t\t<wintitle>Fraction Creator pane</wintitle> and a \n"
                            + "\t\t\t\t<wintitle>Fraction Converter pane</wintitle>. \n" + "\t\t\t </alt> \n"
                            + "\t\t  </image> \n" + "\t\t</p> \n" + "\t\t<p platform=\"macosx\">\n"
                            + "                <image href=\"../Images/mac/WorldTimeProGUI.png\" id=\"image_BEDAF307242F43A5891E9EBA9FDBCAC5\" width=\"813px\"> \n"
                            + "\t\t\t <alt>This graphic shows the fields and buttons in the main \n"
                            + "\t\t\t\t<wintitle>World Time Pro window</wintitle>. The window has a \n"
                            + "\t\t\t\t<wintitle>main calculation pane</wintitle>, a \n"
                            + "\t\t\t\t<wintitle>Fraction Creator pane</wintitle> and a \n"
                            + "\t\t\t\t<wintitle>Fraction Converter pane</wintitle>. \n" + "\t\t\t </alt> \n"
                            + "\t\t  </image> \n" + "\t\t</p> \n" + "\t </section> \n"
                            + "\t <properties id=\"properties_EBCA9E6EE6E546AFBB834EC2879F4F36\"> \n"
                            + "\t\t<prophead> \n" + "\t\t  <proptypehd>Field or button</proptypehd> \n"
                            + "\t\t  <propdeschd>Function</propdeschd> \n" + "\t\t</prophead> \n" + "\t\t<property> \n"
                            + "\t\t  <proptype>\n" + "                  <wintitle>Main calculation pane</wintitle>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Contains the buttons and fields to perform addition,\n"
                            + "\t\t\t subtraction, multiplication and division of units of time.</propdesc> \n"
                            + "\t\t</property> \n" + "\t\t<property> \n"
                            + "\t\t  <proptype>Upper row of entry fields</proptype> \n"
                            + "\t\t  <propdesc>Specifies the first period of time in the\n"
                            + "\t\t\t calculation.</propdesc> \n" + "\t\t</property> \n" + "\t\t<property> \n"
                            + "\t\t  <proptype>Lower row of entry fields</proptype> \n"
                            + "\t\t  <propdesc>Specifies the second period of time in the calculation. \n"
                            + "\t\t\t <note type=\"note\">If you click the \n"
                            + "\t\t\t\t<uicontrol>Multiply</uicontrol> or \n"
                            + "\t\t\t\t<uicontrol>Divide</uicontrol> buttons, the lower row of entry\n"
                            + "\t\t\t\tfields are replaced by the \n"
                            + "\t\t\t\t<uicontrol>Constant</uicontrol> field. \n" + "\t\t\t </note>\n"
                            + "                </propdesc> \n" + "\t\t</property> \n" + "\t\t<property> \n"
                            + "\t\t  <proptype>\n" + "                  <uicontrol>Equals button</uicontrol>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Performs the calculation.</propdesc> \n" + "\t\t</property> \n"
                            + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Result fields</uicontrol>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Display the result of the calculation.</propdesc> \n"
                            + "\t\t</property> \n" + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Operation buttons</uicontrol>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Specifies if the calculation is addition (+), subtraction\n"
                            + "\t\t\t (-), multiplication (x) or division (/).</propdesc> \n" + "\t\t</property> \n"
                            + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Clear button</uicontrol>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Deletes all values from the pane.</propdesc> \n" + "\t\t</property> \n"
                            + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Pass Value button</uicontrol>\n"
                            + "                </proptype> \n" + "\t\t  <propdesc>Moves the value in the \n"
                            + "\t\t\t <uicontrol>result fields</uicontrol> to the upper row of entry\n"
                            + "\t\t\t fields.</propdesc> \n" + "\t\t</property> \n" + "\t\t<property> \n"
                            + "\t\t  <proptype>\n" + "                  <wintitle>Fraction Converter pane</wintitle>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Contains the buttons and fields to convert fractions into\n"
                            + "\t\t\t periods of time.</propdesc> \n" + "\t\t</property> \n" + "\t\t<property> \n"
                            + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Fraction Converter field</uicontrol>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Specifies the fraction to be converted into a period of time.\n"
                            + "\t\t\t \n"
                            + "\t\t\t <note type=\"note\">You specify if the fraction is in hours or minutes\n"
                            + "\t\t\t\tby selecting either \n" + "\t\t\t\t<uicontrol>Hrs</uicontrol> or \n"
                            + "\t\t\t\t<uicontrol>Min</uicontrol> below this field. \n" + "\t\t\t </note>\n"
                            + "                </propdesc> \n" + "\t\t</property> \n" + "\t\t<property> \n"
                            + "\t\t  <proptype>\n" + "                  <uicontrol>Convert button</uicontrol>\n"
                            + "                </proptype> \n" + "\t\t  <propdesc>In the \n"
                            + "\t\t\t <wintitle>Fraction Converter pane</wintitle>, converts a fraction\n"
                            + "\t\t\t into a period of time.</propdesc> \n" + "\t\t</property> \n" + "\t\t<property> \n"
                            + "\t\t  <propdesc>In the \n"
                            + "\t\t\t <wintitle>Fraction Creator pane</wintitle>, converts a period of time\n"
                            + "\t\t\t into a fraction.</propdesc> \n" + "\t\t</property> \n" + "\t\t<property> \n"
                            + "\t\t  <proptype>\n" + "                  <wintitle>Fraction Creator pane</wintitle>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Contains the buttons and fields to convert periods of time\n"
                            + "\t\t\t into fractions.</propdesc> \n" + "\t\t</property> \n" + "\t\t<property> \n"
                            + "\t\t  <proptype>\n" + "                  <uicontrol>Fraction Creator result\n"
                            + "\t\t\t\tfield</uicontrol>\n" + "                </proptype> \n"
                            + "\t\t  <propdesc>Displays the period of time as a fraction of hours, minutes\n"
                            + "\t\t\t or seconds. \n"
                            + "\t\t\t <note type=\"note\">You specify if the fraction is in hours, minutes or\n"
                            + "\t\t\t\tseconds by selecting either \n" + "\t\t\t\t<uicontrol>Hrs</uicontrol>, \n"
                            + "\t\t\t\t<uicontrol>Min</uicontrol> or \n"
                            + "\t\t\t\t<uicontrol>Sec</uicontrol> below this field. \n" + "\t\t\t </note>\n"
                            + "                </propdesc> \n" + "\t\t</property> \n" + "\t </properties> \n"
                            + "  </refbody>\n" + "</reference>\n" + "      </topicrefcontent>\n" + "    </topicref>\n"
                            + "\t<topicrefcontent>\n" + "      <task id=\"calculatingtime\"> \n"
                            + "  <title>Calculating time</title> \n"
                            + "  <shortdesc>This topic describes how to use the \n"
                            + "\t <term>World Time Pro</term> to add, subtract, multiply and divide units of\n"
                            + "\t time.\n" + "  </shortdesc> \n" + "  <prolog> \n"
                            + "\t <author type=\"creator\">Heather Wymer</author>\n" + "\t <copyright> \n"
                            + "\t\t<copyryear year=\"2008\"/> \n" + "\t\t<copyrholder>M-Azlan Software</copyrholder> \n"
                            + "\t </copyright> \n" + "\t <critdates> \n"
                            + "\t\t<created date=\"4 Oct 2008\"/> </critdates>\n" + "\t <metadata> \n"
                            + "\t\t<keywords> \n" + "\t\t  <keyword>add</keyword> \n"
                            + "\t\t  <keyword>subtract</keyword> \n" + "\t\t  <keyword>multiply</keyword> \n"
                            + "\t\t  <keyword>divide</keyword> \n" + "\t\t  <keyword>hours</keyword> \n"
                            + "\t\t  <keyword>minutes</keyword> \n" + "\t\t  <keyword>seconds</keyword> \n"
                            + "\t\t  <keyword>main calculation pane</keyword> \n" + "\t\t</keywords> \n"
                            + "\t\t<prodinfo> \n" + "\t\t  <prodname>World Time Pro</prodname> \n"
                            + "\t\t  <vrmlist> \n" + "\t\t\t <vrm version=\"2 trial\"/> \n" + "\t\t  </vrmlist> \n"
                            + "\t\t</prodinfo> </metadata>\n" + "  </prolog> \n" + "  <taskbody> \n"
                            + "\t <context id=\"context_BBCEFE74A8B549F8894E14BB217F1B13\">This procedure\n"
                            + "\t\texplains how to use the \n"
                            + "\t\t<term>World Time Pro</term> to perform simple calculations on units of\n"
                            + "\t\ttime. For example, you may be managing a two-day sporting event, and need to\n"
                            + "\t\tadd two times together to find a competitor's total time. Using the \n"
                            + "\t\t<term>World Time Pro</term> ensures you can quickly and accurately\n"
                            + "\t\tcalculate the competitor's total time.\n"
                            + "\t\t<note type=\"note\">If you need to use the result of a calculation in\n"
                            + "\t\t  another calculation, click \n"
                            + "\t\t  <uicontrol>Pass Value</uicontrol>. This button copies the values in the\n"
                            + "\t\t  \n"
                            + "\t\t  <uicontrol>result fields</uicontrol> to the upper row of entry fields.\n"
                            + "\t\t</note>\n" + "\t </context> \n"
                            + "\t <steps id=\"steps_FEC436F7E5284103AEFB402CE9C34C23\"> \n"
                            + "\t\t<step id=\"step_BF62E1D0815D460B83D063FBCE9031ED\"> \n" + "\t\t  <cmd>In the \n"
                            + "\t\t\t <wintitle>main calculation pane</wintitle>, type the first time in\n"
                            + "\t\t\t your equation in the upper row of entry fields.\n" + "\t\t  </cmd> \n"
                            + "\t\t</step> \n" + "\t\t<step id=\"step_25AEA05E37EE41B18D487B01821F5563\"> \n"
                            + "\t\t  <cmd>Click the appropriate \n"
                            + "\t\t\t <uicontrol>operation button</uicontrol>.\n" + "\t\t  </cmd> \n"
                            + "\t\t  <stepresult>If you click muliply or divide, the lower row of entry\n"
                            + "\t\t\t fields are replaced with the \n" + "\t\t\t <uicontrol>Constant \n"
                            + "\t\t\t </uicontrol>field.\n" + "\t\t  </stepresult> \n" + "\t\t</step> \n"
                            + "\t\t<step id=\"step_20F3B9F2A52749ECBD2E32111E3DBABD\"> \n"
                            + "\t\t  <cmd>Type the time to add or subtract, or the number to multiply or\n"
                            + "\t\t\t divide by, into the lower row of entry fields.\n" + "\t\t  </cmd> \n"
                            + "\t\t  <info>\n" + "\t\t\t <note type=\"attention\">You must click an \n"
                            + "\t\t\t\t<uicontrol>operation button</uicontrol> before typing numbers in\n"
                            + "\t\t\t\tthe lower row of entry fields. Clicking an \n"
                            + "\t\t\t\t<uicontrol>operation button</uicontrol> deletes all values in the\n"
                            + "\t\t\t\tlower row of entry fields. \n" + "\t\t\t </note>\n" + "\t\t  </info> \n"
                            + "\t\t</step> \n" + "\t\t<step id=\"step_A02D9B92F5A84A559882BD4B01FDAECA\"> \n"
                            + "\t\t  <cmd>Click \n" + "\t\t\t <uicontrol>Equals</uicontrol>.\n" + "\t\t  </cmd> \n"
                            + "\t\t</step> \n" + "\t </steps> \n"
                            + "\t <result id=\"result_16EFD7AED7EE44B28F03613811DABF50\">The result of your\n"
                            + "\t\tcalculation appears in the \n" + "\t\t<uicontrol>result fields</uicontrol>.\n"
                            + "\t </result> \n"
                            + "\t <example id=\"example_AF5E421D610B42BDAFEC3333C8B1C4B7\">For example, to add\n"
                            + "\t\t3 hours 30 min 43 sec and 4 hours 38 min 13 sec, type \n"
                            + "\t\t<userinput>3 30 43</userinput> in the upper row of entry fields, click \n"
                            + "\t\t<uicontrol>Plus</uicontrol>, type \n"
                            + "\t\t<userinput>4 38 13</userinput> in the lower row of entry fields and click\n"
                            + "\t\t\n" + "\t\t<uicontrol>Equals</uicontrol>. The result of \n"
                            + "\t\t<systemoutput>8 hours 8 min 56 sec</systemoutput> appears in the \n"
                            + "\t\t<uicontrol>result fields</uicontrol>.\n" + "\t </example> \n" + "  </taskbody>\n"
                            + "</task>\n" + "    </topicrefcontent>\n" + "  </topicref>\n"
                            + "\t<topicref format=\"dita\" href=\"Tasks/UsingFractionConverter.xml\" locktitle=\"yes\" navtitle=\"Using the fraction converter\" scope=\"local\" type=\"task\">\n"
                            + "    <topicrefcontent>\n" + "      <task id=\"UsingFractionConverter\"> \n"
                            + "  <title>Using the \n" + "\t <term>Fraction Converter</term>\n" + "        </title> \n"
                            + "  <shortdesc>This topic describes how to use the \n"
                            + "\t <term>Fraction Converter</term> to convert \n"
                            + "\t <term>decimal time</term> into time expressed as hours, minutes and\n"
                            + "\t seconds. \n" + "  </shortdesc> \n" + "  <prolog> \n"
                            + "\t <author type=\"creator\">Heather Wymer</author>\n" + "\t <critdates> \n"
                            + "\t\t<created date=\"20 Oct 2008\"/> </critdates>\n" + "\t <metadata> \n"
                            + "\t\t<keywords> \n" + "\t\t  <keyword>Fraction Converter</keyword> \n"
                            + "\t\t  <keyword>Fraction Converter pane</keyword> \n"
                            + "\t\t  <keyword>decimal time</keyword> \n" + "\t\t  <keyword>hours</keyword> \n"
                            + "\t\t  <keyword>minutes</keyword> \n" + "\t\t  <keyword>seconds</keyword> \n"
                            + "\t\t</keywords> \n" + "\t\t<prodinfo> \n"
                            + "\t\t  <prodname>World Time Pro</prodname> \n" + "\t\t  <vrmlist> \n"
                            + "\t\t\t <vrm version=\"2\"/> \n" + "\t\t  </vrmlist> \n" + "\t\t</prodinfo> </metadata>\n"
                            + "  </prolog> \n" + "  <taskbody> \n"
                            + "\t <prereq conref=\"../Reuse/ConrefContent.xml#conreftasks/FractionSectionPrereq\" id=\"prereq_832AD8426A944718BF6DA33E74E6F72C\"/> \n"
                            + "\t <context id=\"context_AAC85BA9E72B4E04985B2F39926C8FEE\">This procedure\n"
                            + "\t\texplains how to convert time expressed as a decimal into time expressed as\n"
                            + "\t\thours, minutes and seconds. \n" + "\t </context> \n"
                            + "\t <steps id=\"steps_87BD6E9A2A3344129703D3A541160A12\"> \n"
                            + "\t\t<step id=\"step_BBADB47B5C814C768431FA0760676389\"> \n" + "\t\t  <cmd>In the \n"
                            + "\t\t\t <wintitle>Fraction Converter pane</wintitle>, type the \n"
                            + "\t\t\t <term>decimal time</term> you want to convert in the \n"
                            + "\t\t\t <uicontrol>Fraction Converter</uicontrol> field. \n" + "\t\t  </cmd> \n"
                            + "\t\t</step> \n" + "\t\t<step id=\"step_5EC889E9FE2F4BFC8024012CF73AEC6D\"> \n"
                            + "\t\t  <cmd>Do one of the following: \n" + "\t\t  </cmd> \n"
                            + "\t\t  <choices id=\"choices_4316708B46964FF78A4078E1453A5886\"> \n"
                            + "\t\t\t <choice id=\"choice_2EED3991541F47C68CD97CC1C3AA7587\">If the \n"
                            + "\t\t\t\t<term>decimal time</term> is in hours, select \n"
                            + "\t\t\t\t<uicontrol>Hrs</uicontrol> below the \n"
                            + "\t\t\t\t<uicontrol>Fraction Converter</uicontrol> field. \n" + "\t\t\t </choice> \n"
                            + "\t\t\t <choice id=\"choice_4B10CB9163DB4FD38C51E984F0ECDFD5\">If the \n"
                            + "\t\t\t\t<term>decimal time</term> is in minutes, select \n"
                            + "\t\t\t\t<uicontrol>Min</uicontrol> below the \n"
                            + "\t\t\t\t<uicontrol>Fraction Converter</uicontrol> field. \n" + "\t\t\t </choice> \n"
                            + "\t\t  </choices> \n" + "\t\t</step> \n"
                            + "\t\t<step id=\"step_16A9D137B8C546E78F04FD26A1A777E4\"> \n" + "\t\t  <cmd>Click \n"
                            + "\t\t\t <uicontrol>Convert</uicontrol>. \n" + "\t\t  </cmd> \n" + "\t\t</step> \n"
                            + "\t </steps> \n"
                            + "\t <result id=\"result_876A2220DB574A3C895FE78986D65866\">The time you converted\n"
                            + "\t\tappears in the \n" + "\t\t<uicontrol>Hrs</uicontrol>, \n"
                            + "\t\t<uicontrol>Min</uicontrol> and \n"
                            + "\t\t<uicontrol>Sec</uicontrol> fields in the \n"
                            + "\t\t<wintitle>Fraction Converter pane</wintitle>. \n" + "\t </result> \n"
                            + "\t <example id=\"example_738B45113FFA459EAC78B984C381828F\">For example, to\n"
                            + "\t\tconvert 10.26 hours into a time expressed as hours, minutes and seconds, in the\n"
                            + "\t\t\n" + "\t\t<wintitle>Fraction Converter pane</wintitle> type \n"
                            + "\t\t<userinput>10.25</userinput> in the \n"
                            + "\t\t<uicontrol>Fraction Converter</uicontrol> field. Select \n"
                            + "\t\t<uicontrol>Hrs</uicontrol> below the \n"
                            + "\t\t<uicontrol>Fraction Converter</uicontrol> field, then click \n"
                            + "\t\t<uicontrol>Convert</uicontrol>. The result of \n"
                            + "\t\t<systemoutput>10 hours 15 min 36 sec</systemoutput> appears in the \n"
                            + "\t\t<uicontrol>Hrs</uicontrol>, \n" + "\t\t<uicontrol>Min</uicontrol> and \n"
                            + "\t\t<uicontrol>Sec</uicontrol> fields in the \n"
                            + "\t\t<wintitle>Fraction Converter pane</wintitle>. \n" + "\t </example> \n"
                            + "  </taskbody>\n" + "</task>\n" + "    </topicrefcontent>\n" + "  </topicref>\n"
                            + "\t<topicref format=\"dita\" href=\"Tasks/UsingDateAnalysis.xml\" locktitle=\"yes\" navtitle=\"Using the Date Analysis Engine\" scope=\"local\" type=\"task\">\n"
                            + "\t\t<topicref format=\"dita\" href=\"Concepts/GregorianCalendar.xml\" locktitle=\"yes\" navtitle=\"About the Gregorian calendar\" scope=\"local\" type=\"concept\">\n"
                            + "      <topicrefcontent>\n" + "        <concept id=\"gregoriancalendar\"> \n"
                            + "  <title>About the Gregorian calendar</title> \n"
                            + "  <shortdesc>This topic explains what the \n"
                            + "\t <term>Gregorian calendar</term> is and why it was introduced.\n" + "  </shortdesc> \n"
                            + "  <prolog> \n" + "\t <author type=\"creator\">Heather Wymer</author>\n"
                            + "\t <copyright> \n" + "\t\t<copyryear year=\"2008\"/> \n"
                            + "\t\t<copyrholder>M-Azlan Software</copyrholder> \n" + "\t </copyright> \n"
                            + "\t <critdates> \n" + "\t\t<created date=\"6 Oct 2008\"/> </critdates>\n"
                            + "\t <metadata> \n" + "\t\t<keywords> \n"
                            + "\t\t  <keyword>Gregorian calendar</keyword> \n"
                            + "\t\t  <keyword>Julian calendar</keyword> \n" + "\t\t  <keyword>leap year</keyword> \n"
                            + "\t\t</keywords> \n" + "\t\t<prodinfo> \n"
                            + "\t\t  <prodname>World Time Pro</prodname> \n" + "\t\t  <vrmlist> \n"
                            + "\t\t\t <vrm version=\"2 trial\"/> \n" + "\t\t  </vrmlist> \n"
                            + "\t\t</prodinfo> </metadata>\n" + "  </prolog> \n" + "  <conbody> \n" + "\t <p>The \n"
                            + "\t\t<term>Gregorian calendar</term> is the calendar used by most societies\n"
                            + "\t\ttoday. It is named after Pope Gregory XIII, who introduced the calendar in\n"
                            + "\t\t1582.\n" + "\t </p> \n" + "\t <p>The \n"
                            + "\t\t<term>Gregorian calendar</term> starts from 1 AD, the year that Jesus\n"
                            + "\t\tChrist was born, although no firm historical evidence has been uncovered to\n"
                            + "\t\tdate the birth of Christ with certainty. The AD suffix stands for the Latin\n"
                            + "\t\tphrase anno Domini, meaning \"in the year of our Lord\". The AD suffix is\n"
                            + "\t\tsometimes replaced with CE (common era), although the numbering of the years\n"
                            + "\t\tdoes not change if the suffix is changed.\n" + "\t </p> \n"
                            + "\t <p>Years prior to the birth of Christ take the suffix BC (before Christ) or\n"
                            + "\t\tBCE (before common era), and are numbered backwards from 1 BC.\n" + "\t </p> \n"
                            + "\t <p>The \n" + "\t\t<term>Gregorian calendar</term> replaced the \n"
                            + "\t\t<term>Julian calendar \n"
                            + "\t\t</term>used by Christian societies in 1582 AD. The \n"
                            + "\t\t<term>Julian calendar</term> mandated that a year was exactly 365.25 days\n"
                            + "\t\tlong, rather than the more accurate 365.2425 days long. The slight inaccuracy\n"
                            + "\t\tin the \n"
                            + "\t\t<term>Julian calendar</term> caused the calendar to become increasingly\n"
                            + "\t\tout of synch with the seasons. To correct the inaccuracy, Pope Gregory deleted\n"
                            + "\t\t10 days from 1582, and changed the method that was used to calculate leap\n"
                            + "\t\tyears.\n" + "\t </p> \n"
                            + "\t <p>A leap year is a year that has one extra day added to February, making\n"
                            + "\t\tthe year 366 days long, rather than the usual 365. The \n"
                            + "\t\t<term>Julian calendar</term> mandated that a leap year should fall on\n"
                            + "\t\tevery year that is divisible by 4. The \n"
                            + "\t\t<term>Gregorian calendar</term> kept this rule, and further specified\n"
                            + "\t\tthat a leap year should not occur in years that are divisible by 100, unless\n"
                            + "\t\tthe year is also divisible by 400. For example, the year 1900 was not a leap\n"
                            + "\t\tyear, but the year 2000 was a leap year. This slight modification allows the \n"
                            + "\t\t<term>Gregorian calendar \n" + "\t\t</term>to stay aligned with the seasons.\n"
                            + "\t </p> \n" + "  </conbody>\n" + "</concept>\n" + "      </topicrefcontent>\n"
                            + "    </topicref>\n"
                            + "\t\t<topicref format=\"dita\" href=\"Reference/DateAnalysisGUI.xml\" locktitle=\"yes\" navtitle=\"The Date Analysis Engine window\" scope=\"local\" type=\"reference\">\n"
                            + "      <topicrefcontent>\n" + "        <reference id=\"dateanalysisgui\"> \n"
                            + "  <title>The<wintitle> Date Analysis Engine window</wintitle>\n"
                            + "          </title> \n"
                            + "  <shortdesc>This topic describes the buttons and fields in the \n"
                            + "\t <wintitle>Date Analysis Engine window</wintitle>. \n" + "  </shortdesc> \n"
                            + "  <prolog> \n" + "\t <author type=\"creator\">Heather Wymer</author>\n"
                            + "\t <copyright> \n" + "\t\t<copyryear year=\"2008\"/> \n"
                            + "\t\t<copyrholder>M-Azlan Software</copyrholder> \n" + "\t </copyright> \n"
                            + "\t <critdates> \n" + "\t\t<created date=\"5 Oct 2008\"/> </critdates>\n"
                            + "\t <metadata> \n" + "\t\t<keywords> \n"
                            + "\t\t  <keyword>Date Analysis Engine</keyword> \n"
                            + "\t\t  <keyword>interface</keyword> \n" + "\t\t  <keyword>calendar pane</keyword> \n"
                            + "\t\t  <keyword>Date Analysis Engine window</keyword> \n"
                            + "\t\t  <keyword>day</keyword> \n" + "\t\t  <keyword>date</keyword> \n"
                            + "\t\t  <keyword>month</keyword> \n" + "\t\t  <keyword>year</keyword> \n"
                            + "\t\t</keywords> \n" + "\t\t<prodinfo> \n"
                            + "\t\t  <prodname>World Time Pro</prodname> \n" + "\t\t  <vrmlist> \n"
                            + "\t\t\t <vrm version=\"2 trial\"/> \n" + "\t\t  </vrmlist> \n"
                            + "\t\t</prodinfo> </metadata>\n" + "  </prolog> \n" + "  <refbody> \n"
                            + "\t <section id=\"section_E0998E7525D94B439272C73B4EDA574A\"> \n" + "\t\t<title>The \n"
                            + "\t\t  <wintitle>Date Analysis Engine window</wintitle>\n" + "              </title>\n"
                            + "              <image height=\"341\" href=\"../Images/win/DateAnalysisGUI.png\" id=\"image_8B5FCAA9A1C6477CB1BE63D92A73A7F3\" width=\"628\"> \n"
                            + "\t\t  <alt>This graphic shows the fields and buttons in the . The window\n"
                            + "\t\t\t contains the and the .<wintitle>Date Analysis Engine\n"
                            + "\t\t\t\twindow</wintitle>\n" + "                  <wintitle>Date Analysis Engine\n"
                            + "\t\t\t\tpane</wintitle>\n" + "                  <wintitle>calendar pane</wintitle> \n"
                            + "\t\t  </alt> \n" + "\t\t</image> \n" + "\t </section> \n"
                            + "\t <properties id=\"properties_F74BD6DB4F8E44119D2E84B9D1BCE8E2\"> \n"
                            + "\t\t<prophead> \n" + "\t\t  <proptypehd>Field or button</proptypehd> \n"
                            + "\t\t  <propdeschd>Function</propdeschd> \n" + "\t\t</prophead> \n" + "\t\t<property> \n"
                            + "\t\t  <proptype>\n" + "                  <uicontrol>Range selector</uicontrol>\n"
                            + "                </proptype> \n" + "\t\t  <propdesc>Inactive in this edition of \n"
                            + "\t\t\t <term>World Time Pro</term>.</propdesc> \n" + "\t\t</property> \n"
                            + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Day drop-down box</uicontrol>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Specifies the day that is used in the calculation.</propdesc>\n"
                            + "\t\t  \n" + "\t\t</property> \n" + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Month drop-down box</uicontrol>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Specifies the month that is used in the\n"
                            + "\t\t\t calculation.</propdesc> \n" + "\t\t</property> \n" + "\t\t<property> \n"
                            + "\t\t  <proptype>\n" + "                  <uicontrol>Year field</uicontrol>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Specifies the year that is used in the\n"
                            + "\t\t\t calculation.</propdesc> \n" + "\t\t</property> \n" + "\t\t<property> \n"
                            + "\t\t  <proptype>\n" + "                  <uicontrol>Analyze button</uicontrol>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Performs the calculation.</propdesc> \n" + "\t\t</property> \n"
                            + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Day Of The Week field</uicontrol>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Displays the day of the week for the date in the \n"
                            + "\t\t\t <uicontrol>Day</uicontrol>, \n" + "\t\t\t <uicontrol>Month</uicontrol> and \n"
                            + "\t\t\t <uicontrol>Year</uicontrol> fields.</propdesc> \n" + "\t\t</property> \n"
                            + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Display Calendar checkbox</uicontrol>\n"
                            + "                </proptype> \n" + "\t\t  <propdesc>Specifies if the \n"
                            + "\t\t\t <wintitle>calendar pane</wintitle> appears.</propdesc> \n" + "\t\t</property> \n"
                            + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Reset button</uicontrol>\n"
                            + "                </proptype> \n" + "\t\t  <propdesc>Deletes the values from the \n"
                            + "\t\t\t <uicontrol>Year</uicontrol> and \n"
                            + "\t\t\t <uicontrol>Day Of The Week</uicontrol> fields, clears the \n"
                            + "\t\t\t <wintitle>calendar pane</wintitle>, changes the value of the \n"
                            + "\t\t\t <uicontrol>Day</uicontrol> field to 1, and changes the value of the \n"
                            + "\t\t\t <uicontrol>Month</uicontrol> field to January.</propdesc> \n"
                            + "\t\t</property> \n" + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Clear button</uicontrol>\n"
                            + "                </proptype> \n" + "\t\t  <propdesc>Deletes the values from the \n"
                            + "\t\t\t <uicontrol>Year</uicontrol> and \n"
                            + "\t\t\t <uicontrol>Day Of The Week</uicontrol> fields, and clears the \n"
                            + "\t\t\t <wintitle>calendar pane</wintitle>.</propdesc> \n" + "\t\t</property> \n"
                            + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Theoretical button</uicontrol>\n"
                            + "                </proptype> \n" + "\t\t  <propdesc>Inactive in this edition of \n"
                            + "\t\t\t <term>World Time Pro</term>.</propdesc> \n" + "\t\t</property> \n"
                            + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Factual button</uicontrol>\n"
                            + "                </proptype> \n" + "\t\t  <propdesc>Inactive in this edition of \n"
                            + "\t\t\t <term>World Time Pro</term>.</propdesc> \n" + "\t\t</property> \n"
                            + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <wintitle>Calendar pane</wintitle>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Displays the days of the week for the month specifed in the \n"
                            + "\t\t\t <uicontrol>Month</uicontrol> and \n"
                            + "\t\t\t <uicontrol>Year</uicontrol> fields.</propdesc> \n" + "\t\t</property> \n"
                            + "\t </properties> \n" + "  </refbody>\n" + "</reference>\n" + "      </topicrefcontent>\n"
                            + "    </topicref>\n" + "\t<topicrefcontent>\n" + "      <task id=\"usingdateanalysis\"> \n"
                            + "  <title>Using the \n" + "\t <term>Date Analysis Engine</term>\n" + "        </title> \n"
                            + "  <shortdesc>This topic describes how to use the \n"
                            + "\t <term>Date Analysis Engine</term> to calculate what day of the week a\n"
                            + "\t specific date is.\n" + "  </shortdesc> \n" + "  <prolog> \n"
                            + "\t <author type=\"creator\">Heather Wymer</author>\n" + "\t <critdates> \n"
                            + "\t\t<created date=\"5 Oct 2008\"/> </critdates>\n" + "\t <metadata> \n"
                            + "\t\t<keywords> \n" + "\t\t  <keyword>calendar pane</keyword> \n"
                            + "\t\t  <keyword>Date Analysis Engine</keyword> \n"
                            + "\t\t  <keyword>Date Analysis Engine window</keyword> \n"
                            + "\t\t  <keyword>date</keyword> \n" + "\t\t  <keyword>day</keyword> \n"
                            + "\t\t  <keyword>month</keyword> \n" + "\t\t  <keyword>year</keyword> \n"
                            + "\t\t  <keyword>Gregorian calendar</keyword> \n" + "\t\t</keywords> \n"
                            + "\t\t<prodinfo> \n" + "\t\t  <prodname>World Time Pro</prodname> \n"
                            + "\t\t  <vrmlist> \n" + "\t\t\t <vrm version=\"2 trial\"/> \n" + "\t\t  </vrmlist> \n"
                            + "\t\t</prodinfo> </metadata>\n" + "  </prolog> \n" + "  <taskbody> \n"
                            + "\t <context id=\"context_C84BE51FBBF241F7B97FB605F852C89F\">The \n"
                            + "\t\t<term>Date Analysis Engine</term> calculates the day of the week for any\n"
                            + "\t\tdate in the range 1 January 1583-31 December 3000. Due to the introduction of\n"
                            + "\t\tthe \n"
                            + "\t\t<term>Gregorian calendar</term> in 1582, dates cannot be correlated to\n"
                            + "\t\tdays of the week prior to this time. The \n"
                            + "\t\t<term>Date Analysis Engine</term> has hundreds of handy uses - for\n"
                            + "\t\texample, you can plan your next year's holidays, or work out the day of the\n"
                            + "\t\tweek on which you were born.\n"
                            + "\t\t<note type=\"note\">To calculate days of the week for dates prior to 1\n"
                            + "\t\t  January 1970, you must buy the Deluxe Edition of \n"
                            + "\t\t  <term>World Time Pro</term>.\n" + "\t\t</note>\n" + "\t </context> \n"
                            + "\t <steps id=\"steps_412C87FA13914E1B8CB7967FD29818EE\"> \n"
                            + "\t\t<step id=\"step_74D06F08A76047FB9F52052EE0EB4F39\"> \n" + "\t\t  <cmd>Select \n"
                            + "\t\t\t <menucascade> \n" + "\t\t\t\t<uicontrol>Options</uicontrol> \n"
                            + "\t\t\t\t<uicontrol>Date Analysis Engine.</uicontrol> \n" + "\t\t\t </menucascade>\n"
                            + "\t\t  </cmd> \n" + "\t\t  <stepresult>The \n"
                            + "\t\t\t <wintitle>Date Analysis Engine window \n" + "\t\t\t </wintitle>opens.\n"
                            + "\t\t  </stepresult> \n" + "\t\t</step> \n"
                            + "\t\t<step id=\"step_00CF7826AC5D41609B6AF8A7A2A681AC\"> \n"
                            + "\t\t  <cmd>Select the date from the \n"
                            + "\t\t\t <uicontrol>Day</uicontrol> drop-down box, and the month from the \n"
                            + "\t\t\t <uicontrol>Month</uicontrol> drop-down box.\n" + "\t\t  </cmd> \n"
                            + "\t\t</step> \n" + "\t\t<step id=\"step_1B799CA38D8F4E139DE97A2034DBD842\"> \n"
                            + "\t\t  <cmd>Type the year in the \n" + "\t\t\t <uicontrol>Year</uicontrol> field.\n"
                            + "\t\t  </cmd> \n" + "\t\t</step> \n"
                            + "\t\t<step id=\"step_BC3B222928954E9FAD2B4E07B715F1C7\"> \n"
                            + "\t\t  <cmd>(Optional) Uncheck \n" + "\t\t\t <uicontrol>Display Calendar</uicontrol>.\n"
                            + "\t\t  </cmd> \n" + "\t\t  <stepresult>The \n"
                            + "\t\t\t <wintitle>calendar pane</wintitle> will not display the calendar for\n"
                            + "\t\t\t the month and year you enter.\n" + "\t\t  </stepresult> \n" + "\t\t</step> \n"
                            + "\t\t<step id=\"step_EEACED14E32A4AD6ABC7E25AE0B90DAF\"> \n" + "\t\t  <cmd>Click \n"
                            + "\t\t\t <uicontrol>Analyze</uicontrol>.\n" + "\t\t  </cmd> \n" + "\t\t</step> \n"
                            + "\t </steps> \n"
                            + "\t <result id=\"result_E719290783764488861ECDD364E21C10\">The day of the week\n"
                            + "\t\tappears in the \n" + "\t\t<uicontrol>Day Of The Week</uicontrol> field and, if \n"
                            + "\t\t<uicontrol>Display Calendar</uicontrol> is selected, the calendar for the\n"
                            + "\t\tmonth and year you entered appears in the \n"
                            + "\t\t<wintitle>calendar pane</wintitle>.\n" + "\t </result> \n"
                            + "\t <example id=\"example_063C8F67E7784AAB8F7A9EF2CB2838B5\">For example, to\n"
                            + "\t\tcalculate the day of the week that 2 February 2000 fell on, open the \n"
                            + "\t\t<term>Date Analysis Engine</term>. Select \n"
                            + "\t\t<userinput>2</userinput> from the \n"
                            + "\t\t<uicontrol>Day</uicontrol> drop-down box, select \n"
                            + "\t\t<userinput>February</userinput> from the \n"
                            + "\t\t<uicontrol>Month</uicontrol> drop-down box, and type \n"
                            + "\t\t<userinput>2000</userinput> in the \n"
                            + "\t\t<uicontrol>Year</uicontrol> field. Click \n"
                            + "\t\t<uicontrol>Enter</uicontrol>. The result of \n"
                            + "\t\t<systemoutput>Thursday</systemoutput> appears in the \n"
                            + "\t\t<uicontrol>Day Of The Week</uicontrol> field, and the calendar for\n"
                            + "\t\tFebruary 2000 appears in the \n" + "\t\t<wintitle>calendar pane</wintitle>.\n"
                            + "\t </example> \n" + "  </taskbody>\n" + "</task>\n" + "    </topicrefcontent>\n"
                            + "  </topicref>\n"
                            + "  <topicref format=\"dita\" href=\"Tasks/UsingFractionCreator.xml\" locktitle=\"yes\" navtitle=\"Using the fraction creator\" scope=\"local\" type=\"task\">\n"
                            + "    <topicrefcontent>\n" + "      <task id=\"UsingFractionCreator\"> \n"
                            + "  <title>Using the \n" + "\t <term>Fraction Creator</term>\n" + "        </title> \n"
                            + "  <shortdesc>This topic describes how to use the \n"
                            + "\t <term>Fraction Creator</term> to turn time expressed as hours, minutes and\n"
                            + "\t seconds into a length of time expressed as a decimal. \n" + "  </shortdesc> \n"
                            + "  <prolog> \n" + "\t <author type=\"creator\">Heather Wymer</author>\n"
                            + "\t <critdates> \n" + "\t\t<created date=\"20 Oct 2008\"/> </critdates>\n"
                            + "\t <metadata> \n" + "\t\t<keywords> \n" + "\t\t  <keyword>Fraction Creator</keyword> \n"
                            + "\t\t  <keyword>Fraction Creator pane</keyword> \n"
                            + "\t\t  <keyword>decimal time</keyword> \n" + "\t\t  <keyword>hours</keyword> \n"
                            + "\t\t  <keyword>minutes</keyword> \n" + "\t\t  <keyword>seconds</keyword> \n"
                            + "\t\t</keywords> \n" + "\t\t<prodinfo> \n"
                            + "\t\t  <prodname>World Time Pro</prodname> \n" + "\t\t  <vrmlist> \n"
                            + "\t\t\t <vrm version=\"2\"/> \n" + "\t\t  </vrmlist> \n" + "\t\t</prodinfo> </metadata>\n"
                            + "  </prolog> \n" + "  <taskbody> \n"
                            + "\t <prereq conref=\"../Reuse/ConrefContent.xml#conreftasks/FractionSectionPrereq\" id=\"prereq_D6F484A0BE5E4015B4C9C1DC0A8AEB53\"/> \n"
                            + "\t <context id=\"context_C4D816BAE6DE4EEF8A540F3C460206FE\">It is tricky to\n"
                            + "\t\tconvert normal time into \n"
                            + "\t\t<term>decimal time</term>. This procedure explains how to use the \n"
                            + "\t\t<term>Fraction Creator</term> to calculate what fraction of time is\n"
                            + "\t\texpressed in time written in hours, minutes and seconds. The fraction that you\n"
                            + "\t\tcreate is expressed as a decimal, and the decimal can be expressed in hours or\n"
                            + "\t\tminutes. \n" + "\t </context> \n"
                            + "\t <steps id=\"steps_0E7191F36C8344FD87FBF10992885E91\"> \n"
                            + "\t\t<step id=\"step_CBD0D24DB1374C03A914E064A24D60A0\"> \n" + "\t\t  <cmd>In the \n"
                            + "\t\t\t <wintitle>Fraction Creator pane</wintitle>, type the time you want to\n"
                            + "\t\t\t convert in the \n" + "\t\t\t <uicontrol>Hrs</uicontrol>, \n"
                            + "\t\t\t <uicontrol>Min</uicontrol> and \n"
                            + "\t\t\t <uicontrol>Sec</uicontrol> fields. \n" + "\t\t  </cmd> \n" + "\t\t</step> \n"
                            + "\t\t<step id=\"step_7F9C41BB5D1F42C49F1635D6867ACAFD\"> \n"
                            + "\t\t  <cmd>Do one of the following: \n" + "\t\t  </cmd> \n"
                            + "\t\t  <choices id=\"choices_565FBF9DC155477A8DEE2841D0D95C83\"> \n"
                            + "\t\t\t <choice id=\"choice_C8C26592C1F24FA6A2283A0807B0CB8D\">To calculate a\n"
                            + "\t\t\t\tfraction in hours, select \n" + "\t\t\t\t<uicontrol>Hrs</uicontrol> below the \n"
                            + "\t\t\t\t<uicontrol>Fraction Creator</uicontrol> result field. \n" + "\t\t\t </choice> \n"
                            + "\t\t\t <choice id=\"choice_7B47CCA0866845C0BB7761C58B2337FF\">To calculate a\n"
                            + "\t\t\t\tfraction in minutes, select \n"
                            + "\t\t\t\t<uicontrol>Min</uicontrol> below the \n"
                            + "\t\t\t\t<uicontrol>Fraction Creator</uicontrol> result field. \n" + "\t\t\t </choice> \n"
                            + "\t\t\t <choice id=\"choice_57939DBBD89D4BD88878306D0A7087F2\">To calculate a\n"
                            + "\t\t\t\tfraction in seconds, select \n"
                            + "\t\t\t\t<uicontrol>Sec</uicontrol> below the \n"
                            + "\t\t\t\t<uicontrol>Fraction Creator</uicontrol> result field. \n" + "\t\t\t </choice> \n"
                            + "\t\t  </choices> \n" + "\t\t</step> \n"
                            + "\t\t<step id=\"step_A7F13431568F4DFF90811E8ABDA3E239\"> \n" + "\t\t  <cmd>Click \n"
                            + "\t\t\t <uicontrol>Convert</uicontrol>. \n" + "\t\t  </cmd> \n" + "\t\t</step> \n"
                            + "\t </steps> \n"
                            + "\t <result id=\"result_585F6BFD00E745C69C7CBDB0AEA8AC26\">The fraction you\n"
                            + "\t\tcalculated appears in the \n"
                            + "\t\t<uicontrol>Fraction Creator</uicontrol> result field. \n" + "\t </result> \n"
                            + "\t <example id=\"example_0418E559B67E4762895805CD22C816D0\">For example, to turn\n"
                            + "\t\t2 hours 35 min 16 sec into a fraction expressed in hours, in the \n"
                            + "\t\t<wintitle>Fraction Creator pane</wintitle> type \n"
                            + "\t\t<userinput>2</userinput> in the \n" + "\t\t<uicontrol>Hrs</uicontrol> field, \n"
                            + "\t\t<userinput>35</userinput> in the \n" + "\t\t<uicontrol>Min</uicontrol> field and \n"
                            + "\t\t<userinput>16</userinput> in the \n"
                            + "\t\t<uicontrol>Sec</uicontrol> field. Select \n"
                            + "\t\t<uicontrol>Hrs</uicontrol> below the \n"
                            + "\t\t<uicontrol>Fraction Creator</uicontrol> result field, and click \n"
                            + "\t\t<uicontrol>Convert</uicontrol>. The result of \n"
                            + "\t\t<systemoutput>2.5877777</systemoutput> appears in the \n"
                            + "\t\t<uicontrol>Fraction Creator</uicontrol> result field. \n" + "\t </example> \n"
                            + "  </taskbody>\n" + "</task>\n" + "    </topicrefcontent>\n" + "  </topicref>\n"
                            + "\t<topicref format=\"dita\" href=\"Tasks/ConvertingMilitaryTime.xml\" locktitle=\"yes\" navtitle=\"Converting to or from military time\" scope=\"local\" type=\"task\">\n"
                            + "\t\t<topicref format=\"dita\" href=\"Concepts/MilitaryTime.xml\" locktitle=\"yes\" navtitle=\"About military time\" scope=\"local\" type=\"concept\">\n"
                            + "      <topicrefcontent>\n" + "        <concept id=\"militarytime\"> \n"
                            + "  <title>About \n" + "\t <term>military time</term>\n" + "          </title> \n"
                            + "  <shortdesc>This topic explains what \n"
                            + "\t <term>military time</term> is and why it is used.\n" + "  </shortdesc> \n"
                            + "  <prolog> \n" + "\t <author type=\"creator\">Heather Wymer</author>\n"
                            + "\t <copyright> \n" + "\t\t<copyryear year=\"2008\"/> \n"
                            + "\t\t<copyrholder>M-Azlan Software</copyrholder> \n" + "\t </copyright> \n"
                            + "\t <critdates> \n" + "\t\t<created date=\"6 Oct 2008\"/> </critdates>\n"
                            + "\t <metadata> \n" + "\t\t<keywords> \n" + "\t\t  <keyword>military time</keyword> \n"
                            + "\t\t  <keyword>24-hour clock</keyword> \n" + "\t\t  <keyword>standard time</keyword> \n"
                            + "\t\t</keywords> \n" + "\t\t<prodinfo> \n"
                            + "\t\t  <prodname>World Time Pro</prodname> \n" + "\t\t  <vrmlist> \n"
                            + "\t\t\t <vrm version=\"2 trial\"/> \n" + "\t\t  </vrmlist> \n"
                            + "\t\t</prodinfo> </metadata>\n" + "  </prolog> \n" + "  <conbody> \n" + "\t <p>\n"
                            + "              <term>Military time</term> refers to a timekeeping system where the\n"
                            + "\t\thours of the day are numbered 0-24, rather than the \n"
                            + "\t\t<term>standard time</term> system's numbering of 1-12 am and 1-12 pm. \n"
                            + "\t\t<term>Military time</term> is also called the \n"
                            + "\t\t<term>24-hour clock</term>. \n" + "\t </p> \n" + "\t <p>\n"
                            + "              <term>Military time</term> is written in the format hh.mm, where h=hours\n"
                            + "\t\tand m=minutes. Between 1.00 am and 12.59 pm \n"
                            + "\t\t<term>military time</term> and \n"
                            + "\t\t<term>standard time</term> look very similar. For example, 4.30 am \n"
                            + "\t\t<term>standard time</term> is written as 04.30 in \n"
                            + "\t\t<term>military time</term>. However, after 12.59 pm it becomes slightly\n"
                            + "\t\tmore difficult to correlate \n" + "\t\t<term>military time</term> and \n"
                            + "\t\t<term>standard time</term>. For example, 6.08 pm \n"
                            + "\t\t<term>standard time</term> is written as 18.08 in \n"
                            + "\t\t<term>military time</term>. \n" + "\t </p> \n"
                            + "\t <p>After 12.59 pm, an easy way to convert \n" + "\t\t<term>military time</term> to \n"
                            + "\t\t<term>standard time</term> is to subtract 12 hours from the \n"
                            + "\t\t<term>military time</term> then add the pm suffix. For example,\n"
                            + "\t\tsubtracting 12 hours from the \n"
                            + "\t\t<term>military time</term> of 17.45 gives the \n"
                            + "\t\t<term>standard time</term> of 5.45 pm.\n" + "\t </p> \n"
                            + "\t <p>Midnight can be expressed as either 00.00 or 24.00 in \n"
                            + "\t\t<term>military time</term>. In practise, 00.00 is used to refer to the\n"
                            + "\t\tstart of a day, and 24.00 to refer to the end of a day. \n" + "\t </p> \n"
                            + "\t <p>As the name suggests, \n"
                            + "\t\t<term>military time</term> is used by the military to avoid potentially\n"
                            + "\t\tdangerous situations that may result if soldiers misunderstand \n"
                            + "\t\t<term>standard time</term>'s am or pm suffix. \n"
                            + "\t\t<term>Military time</term> is used in other industries where time is\n"
                            + "\t\tcritical, such as computing, aviation, railway timetables and medical\n"
                            + "\t\tsituations. \n" + "\t\t<term>Military time</term> is the \n"
                            + "\t\t<term>ISO</term> international standard for the notation of time, and is\n"
                            + "\t\tused as instead of \n"
                            + "\t\t<term>standard time</term> in many countries, especially in Europe.\n" + "\t </p> \n"
                            + "  </conbody> \n" + "</concept>\n" + "      </topicrefcontent>\n" + "    </topicref>\n"
                            + "\t\t<topicref format=\"dita\" href=\"Reference/MilitaryTimeGUI.xml\" locktitle=\"yes\" navtitle=\"The Standard/Military Time Converter window\" scope=\"local\" type=\"reference\">\n"
                            + "      <topicrefcontent>\n" + "        <reference id=\"militarytimegui\"> \n"
                            + "  <title>The \n" + "\t <wintitle>Standard/Military Time Converter window</wintitle>\n"
                            + "          </title> \n"
                            + "  <shortdesc>This topic describes the buttons and fields on the \n"
                            + "\t <wintitle>Standard/Military Time Converter window</wintitle>. \n"
                            + "  </shortdesc> \n" + "  <prolog> \n"
                            + "\t <author type=\"creator\">Heather Wymer</author>\n" + "\t <copyright> \n"
                            + "\t\t<copyryear year=\"2008\"/> \n" + "\t\t<copyrholder>M-Azlan Software</copyrholder> \n"
                            + "\t </copyright> \n" + "\t <critdates> \n"
                            + "\t\t<created date=\"5 Oct 2008\"/> </critdates>\n" + "\t <metadata> \n"
                            + "\t\t<keywords> \n" + "\t\t  <keyword>Standard/Military Time Converter</keyword> \n"
                            + "\t\t  <keyword>interface</keyword> \n" + "\t\t  <keyword>military time</keyword> \n"
                            + "\t\t  <keyword>standard time</keyword> \n" + "\t\t</keywords> \n" + "\t\t<prodinfo> \n"
                            + "\t\t  <prodname>World Time Pro</prodname> \n" + "\t\t  <vrmlist> \n"
                            + "\t\t\t <vrm version=\"2 trial\"/> \n" + "\t\t  </vrmlist> \n"
                            + "\t\t</prodinfo> </metadata>\n" + "  </prolog> \n" + "  <refbody> \n"
                            + "\t <section id=\"section_7276B18487AF4FEDA0E402F10C027D73\"> \n" + "\t\t<title>The \n"
                            + "\t\t  <wintitle>Standard/Military Time Converter\n" + "\t\t\t window</wintitle>\n"
                            + "              </title>\n"
                            + "              <image height=\"313\" href=\"../Images/win/MilitaryTimeGUI.png\" id=\"image_DCECCC134F314309AC111172B013363D\" width=\"339\"> \n"
                            + "\t\t  <alt>This graphic shows the fields and buttons in the\n"
                            + "\t\t\t .<wintitle>Standard/Military Time Converter window</wintitle> \n"
                            + "\t\t  </alt> \n" + "\t\t</image> \n" + "\t </section> \n"
                            + "\t <properties id=\"properties_2F9AC531BF4B4E6B8A24AD05DAA3BD39\"> \n"
                            + "\t\t<prophead> \n" + "\t\t  <proptypehd>Field or button</proptypehd> \n"
                            + "\t\t  <propdeschd>Function</propdeschd> \n" + "\t\t</prophead> \n" + "\t\t<property> \n"
                            + "\t\t  <proptype>\n" + "                  <uicontrol>? button</uicontrol>\n"
                            + "                </proptype> \n" + "\t\t  <propdesc>Opens the help.</propdesc> \n"
                            + "\t\t</property> \n" + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Standard time converter</uicontrol>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Specifies that the calculation converts \n"
                            + "\t\t\t <term>military time</term> to \n"
                            + "\t\t\t <term>standard time</term>.</propdesc> \n" + "\t\t</property> \n"
                            + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Military time converter</uicontrol>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Specifies that the calculation converts \n"
                            + "\t\t\t <term>standard time</term> to \n"
                            + "\t\t\t <term>military time</term>.</propdesc> \n" + "\t\t</property> \n"
                            + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Military Time fields</uicontrol>\n"
                            + "                </proptype> \n" + "\t\t  <propdesc>If the \n"
                            + "\t\t\t <uicontrol>Standard time converter</uicontrol> is selected, specifies\n"
                            + "\t\t\t the \n" + "\t\t\t <term>military time</term> to be converted.</propdesc> \n"
                            + "\t\t</property> \n" + "\t\t<property> \n" + "\t\t  <propdesc>If the \n"
                            + "\t\t\t <uicontrol>Military time converter</uicontrol> is selected, displays\n"
                            + "\t\t\t the result of a \n"
                            + "\t\t\t <term>standard time</term> conversion.</propdesc> \n" + "\t\t</property> \n"
                            + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Convert button</uicontrol>\n"
                            + "                </proptype> \n" + "\t\t  <propdesc>If the \n"
                            + "\t\t\t <uicontrol>Standard time converter</uicontrol> is selected, converts \n"
                            + "\t\t\t <term>military time</term> to \n"
                            + "\t\t\t <term>standard time</term>.</propdesc> \n" + "\t\t</property> \n"
                            + "\t\t<property> \n" + "\t\t  <propdesc>If the \n"
                            + "\t\t\t <uicontrol>Military time converter</uicontrol> is selected, converts \n"
                            + "\t\t\t <term>standard time</term> to \n"
                            + "\t\t\t <term>military time</term>.</propdesc> \n" + "\t\t</property> \n"
                            + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Standard Time fields</uicontrol>\n"
                            + "                </proptype> \n" + "\t\t  <propdesc>If the \n"
                            + "\t\t\t <uicontrol>Standard time converter</uicontrol> is selected, displays\n"
                            + "\t\t\t the result of a \n"
                            + "\t\t\t <term>military time</term> conversion.</propdesc> \n" + "\t\t</property> \n"
                            + "\t\t<property> \n" + "\t\t  <propdesc>If the \n"
                            + "\t\t\t <uicontrol>Military time converter</uicontrol> is selected, specifies\n"
                            + "\t\t\t the \n" + "\t\t\t <term>standard time</term> to be converted.</propdesc> \n"
                            + "\t\t</property> \n" + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>AM/PM drop-down box</uicontrol>\n"
                            + "                </proptype> \n" + "\t\t  <propdesc>Specifies if the \n"
                            + "\t\t\t <term>standard time</term> displayed is AM or PM.</propdesc> \n"
                            + "\t\t</property> \n" + "\t\t<property> \n" + "\t\t  <proptype>\n"
                            + "                  <uicontrol>Reset button</uicontrol>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Deletes all values from the window and selects the \n"
                            + "\t\t\t <uicontrol>Standard time converter</uicontrol> if it is not already\n"
                            + "\t\t\t selected.</propdesc> \n" + "\t\t</property> \n" + "\t\t<property> \n"
                            + "\t\t  <proptype>\n" + "                  <uicontrol>Clear button</uicontrol>\n"
                            + "                </proptype> \n"
                            + "\t\t  <propdesc>Deletes all vaules from the window.</propdesc> \n" + "\t\t</property> \n"
                            + "\t </properties> \n" + "  </refbody>\n" + "</reference>\n" + "      </topicrefcontent>\n"
                            + "    </topicref>\n" + "\t<topicrefcontent>\n"
                            + "      <task id=\"convertingmilitarytime\"> \n" + "  <title>Converting to or from \n"
                            + "\t <term>military time</term>\n" + "        </title> \n"
                            + "  <shortdesc>This topic describes how to convert \n"
                            + "\t <term>military time</term> to \n" + "\t <term>standard time</term>, or \n"
                            + "\t <term>standard time</term> to \n" + "\t <term>military time</term>.\n"
                            + "  </shortdesc> \n" + "  <prolog> \n"
                            + "\t <author type=\"creator\">Heather Wymer</author>\n" + "\t <critdates> \n"
                            + "\t\t<created date=\"5 Oct 2008\"/> </critdates>\n" + "\t <metadata> \n"
                            + "\t\t<keywords> \n" + "\t\t  <keyword>standard time</keyword> \n"
                            + "\t\t  <keyword>military time</keyword> \n"
                            + "\t\t  <keyword>Standard/Military Time Converter</keyword> \n"
                            + "\t\t  <keyword>Standard/Military Time Converter window</keyword> \n"
                            + "\t\t</keywords> \n" + "\t\t<prodinfo> \n"
                            + "\t\t  <prodname>World Time Pro</prodname> \n" + "\t\t  <vrmlist> \n"
                            + "\t\t\t <vrm version=\"2 trial\"/> \n" + "\t\t  </vrmlist> \n"
                            + "\t\t</prodinfo> </metadata>\n" + "  </prolog> \n" + "  <taskbody> \n"
                            + "\t <context id=\"context_6D3E7D805B284AEB9C7BC71846F05BC1\">\n"
                            + "            <term>Military\n"
                            + "\t\t  time</term> is used by the armed forces to avoid confusion between the hours of\n"
                            + "\t\tthe morning and afternoon, and is also used in many European countries. This\n"
                            + "\t\tprocedure describes a quick way to accurately convert \n"
                            + "\t\t<term>military time</term> to \n" + "\t\t<term>standard time</term>, or \n"
                            + "\t\t<term>standard time</term> to \n" + "\t\t<term>military time</term>.\n"
                            + "\t </context> \n" + "\t <steps id=\"steps_716EF0F340B741B8BAAEFB58B0A70B8E\"> \n"
                            + "\t\t<step id=\"step_9408A7177A3C418980F3C1B7C988E5A5\"> \n" + "\t\t  <cmd>Select \n"
                            + "\t\t\t <menucascade> \n" + "\t\t\t\t<uicontrol>Options</uicontrol> \n"
                            + "\t\t\t\t<uicontrol>Standard/Military Time Converter.</uicontrol> \n"
                            + "\t\t\t </menucascade>\n" + "\t\t  </cmd> \n" + "\t\t  <stepresult>The \n"
                            + "\t\t\t <wintitle>Standard/Military Time Converter window</wintitle> opens.\n"
                            + "\t\t  </stepresult> \n" + "\t\t</step> \n"
                            + "\t\t<step id=\"step_4932CDD6BE124D598F4E186D8FD307AC\"> \n"
                            + "\t\t  <cmd>Do one of the following:\n" + "\t\t  </cmd> \n"
                            + "\t\t  <choices id=\"choices_77415AEE544844629D1D8BBDD56728ED\"> \n"
                            + "\t\t\t <choice id=\"choice_C0EFC75249BC4695A40E471E853102B4\">To convert from \n"
                            + "\t\t\t\t<term>military time</term> to \n"
                            + "\t\t\t\t<term>standard time</term>, ensure the \n"
                            + "\t\t\t\t<uicontrol>Standard time converter</uicontrol> is selected.\n"
                            + "\t\t\t </choice> \n"
                            + "\t\t\t <choice id=\"choice_D1D88F1F17D04D3BA45C6F4B4CC267AD\">To convert from \n"
                            + "\t\t\t\t<term>standard time</term> to \n"
                            + "\t\t\t\t<term>military time</term>, select the \n"
                            + "\t\t\t\t<uicontrol>Military time converter</uicontrol>.\n" + "\t\t\t </choice> \n"
                            + "\t\t  </choices> \n" + "\t\t</step> \n"
                            + "\t\t<step id=\"step_2BF9D35CB6344D1FA4B59EE231518AF4\"> \n"
                            + "\t\t  <cmd>Do one of the following:\n" + "\t\t  </cmd> \n"
                            + "\t\t  <choices id=\"choices_F4E844972AF54C43834246E1AD4EE2E3\"> \n"
                            + "\t\t\t <choice id=\"choice_E2410DF24A2A407FBF58454AACE0C549\">To convert from \n"
                            + "\t\t\t\t<term>military time</term> to \n"
                            + "\t\t\t\t<term>standard time</term>, type the time you want to convert in\n"
                            + "\t\t\t\tthe \n" + "\t\t\t\t<uicontrol>Military Time</uicontrol> fields.\n"
                            + "\t\t\t </choice> \n" + "\t").replace("\n\n", "\n")));
        } catch (final TransformerException e) {
            e.printStackTrace();
        }
    }

    @SuppressWarnings("ConstantConditions")
    @Test
    public void containsPublicIdAndSystemId()
    {
        final ClassLoader classLoader = getClass().getClassLoader();
        final File file = new File(classLoader.getResource("DITA/WorldTimePro.ditamap").getFile());
        DitaBuilder ditaBuilder;
        try {
            ditaBuilder = new DitaBuilder(file.toURI().toURL(), null);
            final String andResolveAllTopicRefs = ditaBuilder.findAndResolveAllTopicRefs();
            assertTrue(andResolveAllTopicRefs.contains("<!DOCTYPE map PUBLIC \"-//OASIS//DTD DITA Map//EN\""));
            assertTrue(andResolveAllTopicRefs.contains("\"http://docs.oasis-open.org/dita/v1.2/OS/dtd/map.dtd\""));
        } catch (final Exception e) {
            //
        }
    }

}