name: Create Javadoc and Tag
on:
  workflow_dispatch:

jobs:
  Create-Javadoc-And-Tag:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Create Javadoc
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a
        with:
          arguments: javadoc

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          CUSTOM_TAG: ${{ steps.deploy.outputs.TAGNAME }}

      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: "docs/"
