name: Create Javadoc and Tag
on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag for Release'
        type: string
        required: true

jobs:
  Create-Javadoc-And-Tag:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Create Javadoc
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2
        with:
          arguments: javadoc

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          CUSTOM_TAG: ${{ inputs.tagName }}

      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: "docs/"
