name: Build and Deploy
on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.CODE_SIGNING_PWD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.CODE_SIGNING_PRIV_KEY }}
      ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PW }}
      ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Gradle build
        uses: gradle/gradle-build-action@b5126f31dbc19dd434c3269bf8c28c315e121da2
        with:
          arguments: build

      - name: Create Javadoc
        uses: gradle/gradle-build-action@b5126f31dbc19dd434c3269bf8c28c315e121da2
        with:
          arguments: javadoc

      - name: Deploy artifacts
        id: deploy
        if: github.ref == 'refs/heads/main'
        run: |
          ./gradlew publishToSonatype closeAndReleaseStagingRepository --stacktrace --warning-mode all

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        if: steps.deploy.outputs.RELEASE == 'true' && github.ref == 'refs/heads/main'
        env:
          CUSTOM_TAG: ${{ steps.deploy.outputs.TAGNAME }}

      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        if: steps.deploy.outputs.RELEASE == 'true' && github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: "docs/"
