name: Release Snapshot Version
on:
  workflow_dispatch:

jobs:
  Release-Snapshot:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.CODE_SIGNING_PWD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.CODE_SIGNING_PRIV_KEY }}
      ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PW }}
      ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4

      - name: Gradle build
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2
        with:
          arguments: build

      - name: Deploy artifacts
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2
        with:
          arguments: publishToSonatype --stacktrace
