name: Release Stable Version
on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  Release-Stable:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.CODE_SIGNING_PWD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.CODE_SIGNING_PRIV_KEY }}
      ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PW }}
      ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4

      - name: Gradle build
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2
        with:
          arguments: build

      - name: Remove Snapshot Suffix
        id: removeSnapshot
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2
        with:
          arguments: removeSnapshotSuffix

      - name: Commit Current Version
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email ${{ env.GITHUB_MACHINE_USER_EMAIL }}
          git commit -m "Release v${{ steps.removeSnapshot.TAGNAME }}"

      - name: Create Javadoc
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2
        with:
          arguments: javadoc

      - name: Deploy Artifacts
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2
        with:
          arguments: publishToSonatype closeAndReleaseStagingRepository --stacktrace

      - name: Create and Push Tag
        run: git tag ${{ steps.removeSnapshot.TAGNAME }}

      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: "docs/"

      - name: Increment Snapshot Version
        id: incrementSnapshotVersion
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2
        with:
          arguments: incrementSnapshotVersion

      - name: Commit Snapshot Suffix
        run: git commit -m "Update version from ${{ steps.incrementSnapshotVersion.OLDVERSION }} to ${{ steps.incrementSnapshotVersion.NEWVERSION }}"

      - name: Push Changes
        run: git push origin main

      - name: Create Draft Release
        run: gh release create ${{ steps.removeSnapshot.TAGNAME }} --verify-tag --draft --generate-notes
