name: Release Stable Version
on:
  workflow_dispatch:
    inputs:
      tagName:
        description: Tag to Release
        required: true
        type: string

jobs:
  Release-Stable:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.CODE_SIGNING_PWD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.CODE_SIGNING_PRIV_KEY }}
      ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PW }}
      ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Gradle build
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2
        with:
          arguments: build

      - name: Create Javadoc
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2
        with:
          arguments: javadoc

      - name: Deploy artifacts
        id: deploy
        if: github.ref == 'refs/heads/main'
        run: |
          ./gradlew publishToSonatype closeAndReleaseStagingRepository --stacktrace

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        if: steps.deploy.outputs.RELEASE == 'true' && github.ref == 'refs/heads/main'
        env:
          CUSTOM_TAG: ${{ inputs.tagName }}

      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        if: steps.deploy.outputs.RELEASE == 'true' && github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: "docs/"
