name: Release Snapshot Version
on:
  workflow_dispatch:

jobs:
  Release-Snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Check ref_type
        if: github.ref_type != 'branch'
        run: |
          echo "This workflow can only be triggered on a branch!"
          exit 1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@27152f6fa06a6b8062ef7195c795692e51fc2c81

      - name: Gradle build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Publish Artifacts
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: publishToSonatype --stacktrace
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.CODE_SIGNING_PRIV_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.CODE_SIGNING_PWD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PW }}
