name: Release Snapshot Version
on:
  workflow_dispatch:

jobs:
  Release-Snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle build
        run: ./gradlew build

      - name: Publish Artifacts
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.CODE_SIGNING_PRIV_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.CODE_SIGNING_PWD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PW }}
        run: ./gradlew publishToSonatype
