name: Release Stable Version
on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  Release-Stable:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.CODE_SIGNING_PWD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.CODE_SIGNING_PRIV_KEY }}
      ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PW }}
      ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Gradle build
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2
        with:
          arguments: build

      - name: Remove Snapshot Suffix
        id: removeSnapshot
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a
        with:
          arguments: removeSnapshotSuffix

      - name: Remove Snapshot Suffix
        run: |
          git config --global user.name 'acrolinx-machine-user-for-integrations'
          git config --global user.email 'danjela.lura@acrolinx.net'
          git commit -m "Release v${{ steps.removeSnapshot.TAGNAME }}"

      - name: Create Javadoc
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2
        with:
          arguments: javadoc

      - name: Deploy Artifacts
        if: github.ref == 'refs/heads/main'
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a
        with:
          arguments: publishToSonatype closeAndReleaseStagingRepository --stacktrace

      - name: Create and Push Tag
        run: |
          git tag ${{ steps.removeSnapshot.TAGNAME }}

      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        if: steps.deploy.outputs.RELEASE == 'true' && github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: "docs/"

      - name: Increment Snapshot Version
        id: incrementSnapshotVersion
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a
        with:
          arguments: incrementSnapshotVersion

      - name: Commit Snapshot Suffix
        run: git commit -m "Update version from ${{ steps.incrementSnapshotVersion.OLDVERSION }} to ${{ steps.incrementSnapshotVersion.NEWVERSION }}"

      - name: Push Changes to Main
        run: git push origin main
