name: Release Stable Version
on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  Release-Stable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4

      - name: Gradle build
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa
        with:
          arguments: build
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Remove Snapshot Suffix
        id: removeSnapshotSuffix
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa
        with:
          arguments: removeSnapshotSuffix

      - name: Commit Current Version
        env:
          OLD_SNAPSHOT_VERSION: ${{ steps.removeSnapshotSuffix.outputs.OLD_SNAPSHOT_VERSION }}
          RELEASE_VERSION: ${{ steps.removeSnapshotSuffix.outputs.RELEASE_VERSION }}
        run: |
          git config user.name ${{ github.actor }}
          git config user.email opensource@acrolinx.com
          git add gradle.properties
          git commit -m "Update version from $OLD_SNAPSHOT_VERSION to $RELEASE_VERSION"

      - name: Create Tag Name
        id: createTagName
        env:
          RELEASE_VERSION: ${{ steps.removeSnapshotSuffix.outputs.RELEASE_VERSION }}
        run: echo "TAG_NAME=release-$RELEASE_VERSION" >> "$GITHUB_OUTPUT"

      - name: Create Tag
        env:
          TAG_NAME: ${{ steps.createTagName.outputs.TAG_NAME }}
        run: git tag $TAG_NAME

      - name: Publish Artifacts
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa
        with:
          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository --stacktrace
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.CODE_SIGNING_PRIV_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.CODE_SIGNING_PWD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PW }}

      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: "build/docs/javadoc/"

      - name: Increment Version and Add Snapshot Suffix
        id: incrementSnapshotVersion
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa
        with:
          arguments: incrementSnapshotVersion

      - name: Commit New Snapshot Version
        env:
          RELEASE_VERSION: ${{ steps.removeSnapshotSuffix.outputs.RELEASE_VERSION }}
          NEW_SNAPSHOT_VERSION: ${{ steps.incrementSnapshotVersion.outputs.NEW_SNAPSHOT_VERSION }}
        run: |
          git add gradle.properties
          git commit -m "Update version from $RELEASE_VERSION to $NEW_SNAPSHOT_VERSION"

      - name: Push Changes
        env:
          TAG_NAME: ${{ steps.createTagName.outputs.TAG_NAME }}
        run: git push --atomic --set-upstream origin HEAD $TAG_NAME

      - name: Create Draft Release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ steps.createTagName.outputs.TAG_NAME }}
        run: gh release create $TAG_NAME --title $TAG_NAME --verify-tag --draft
